### ISSUE TITLE
Setup in FreeBSD 9.3 jail fails with ImportError: No module named Crypto.Cipher

### ISSUE THREAD

**Issue by sysfu** [cryptodotis/mixfaster#2]
Trying to build Mixfaster in a FreeBSD 9.3 jails and it fails with this message after keying in the statistics server.

```
root@mix:/usr/local/src/mixfaster # ./setup.py 

Where do you want to download your statistics from?
   If you don't know, use http://pinger.mixmin.net
http://pinger.mixmin.net

Traceback (most recent call last):
  File "./setup.py", line 30, in <module>
    from app.model.mixKey import *
  File "/usr/local/src/mixfaster/app/model/mixKey.py", line 5, in <module>
    from Crypto.Cipher import DES3
ImportError: No module named Crypto.Cipher
```

**Comment by sysfu** [comment]
Solved by installing py27-pycrypto pkg. You'll also want to install py27-gnupg and gnupg.
